<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:tns="http://www.tibco.com/InizializeResubmitConfig/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="InizializeResubmitConfig" targetNamespace="http://www.tibco.com/InizializeResubmitConfig/" xmlns:xsd1="http://www.example.org/InitializeDB">
    <wsdl:types>
    	<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    		<xsd:import namespace="http://www.example.org/InitializeDB"
    			schemaLocation="../Schemas/InitializeDB.xsd">
    		</xsd:import></xsd:schema></wsdl:types>
    <wsdl:message name="InitializeRequest">
		<wsdl:part name="parameters"
			element="xsd1:ResubmitConfMultiple">
		</wsdl:part>
    </wsdl:message>
    <wsdl:message name="InitializeResponse">
    	<wsdl:part name="parameters" element="xsd1:Result"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="ResubmitConf">
    	<wsdl:operation name="Initialize">
    		<wsdl:input message="tns:InitializeRequest"></wsdl:input>
    		<wsdl:output message="tns:InitializeResponse"></wsdl:output>
    	</wsdl:operation>
    </wsdl:portType></wsdl:definitions>
